name: ghaction-build-pkg-volt-engine
run-name: BUILD${{ github.run_number }}-${{ github.event.repository.name }}-${{ github.workflow }}_${{ github.ref_name }}
on:
  push:
    branches:
      - dev*
      - main
jobs:
    call-github-python-pytests-workflow:
      uses: fereol023/pipelines_templates/.github/workflows/github-pypi-build-package.yml@main
      secrets:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}       