name: ghaction-ci-volt-engine
run-name: CI${{ github.run_number }}-${{ github.event.repository.name }}-${{ github.workflow }}_${{ github.ref_name }}
on:
  push:
    branches:
      - dev*
      - main
jobs:
    call-github-python-pytests-workflow:
      uses: fereol023/pipelines_templates/.github/workflows/github-python-pytests.yml@main
      secrets:
        PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
       